### PR TITLE
fix: change package.json (tui-release-notes address change) / 'template' option add to optionsProps 

### PR DESCRIPTION
**Pull request by awer000**
### Please check if the PR fulfills these requirements
- [ ] It's the right issue type on the title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has a description of the breaking change

### Description

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

### CODE REVIEW

**Comment by awer000** [comment]
The address "https://github.com/nhn/tui.release-notes.git" is now 404. Then I changed new address "https://github.com/nhn/toast-ui.release-notes.git"

**Comment by jungeun-cho** [comment]
@awer000
Please do not commit the `yarn.lock` file.
I will upload the installation version management to the `package-lock.json` file.

**Comment by awer000** [comment]
@jungeun-cho 
Thank you for your comment. I removed yarn.lock file.

**Review by jungeun-cho — APPROVED** [review]
Thanks for your contribution!

**Pull request merged**
